---
#eureka:
#  instance:
#    hostname: localhost #指定主机地址
#  client:
#    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
#    register-with-eureka: false
#server:
#  port: 8000
server:
  port: 8000
spring:
  application:
    name: eureka-server
  profiles: reg1
eureka:
  instance:
    hostname: replical1
  client:
    serviceUrl:
      defaultZone: http://replical2:8111/eureka/,http://replical3:8222/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true
---
server:
  port: 8111
spring:
  application:
    name: eureka-server
  profiles: reg2
eureka:
  instance:
    hostname: replical2
  client:
    serviceUrl:
      defaultZone: http://replical1:8000/eureka/,http://replical3:8222/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true
---
server:
  port: 8222
spring:
  application:
    name: eureka-server
  profiles: reg3
eureka:
  instance:
    hostname: replical3
  client:
    serviceUrl:
      defaultZone: http://replical1:8000/eureka/,http://replical2:8111/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true