#eureka:
#  instance:
#    hostname: localhost #指定主机地址
#  client:
#    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
#    register-with-eureka: false
#server:
#  port: 8000
server:
  port: 8001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replical2
  client:
    serviceUrl:
      defaultZone: http://replical1:8000/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true