server:
  port: 8087
eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://replical1:8000/eureka/,http://replical2:8111/eureka/,http://replical3:8222/eureka/
spring:
  application:
    name: shop-cart-api
